[tool.poetry]
name = "mlproject"
version = "0.1.0"
description = ""
authors = ["mariosajdini <t8200003@aueb.gr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
